//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstapproach_EntityProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB65_001Entities2 : DbContext
    {
        public DB65_001Entities2()
            : base("name=DB65_001Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcountry> tblcountries { get; set; }
        public virtual DbSet<tblemployee> tblemployees { get; set; }
        public virtual DbSet<tblstate> tblstates { get; set; }
    }
}
