//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstapproach_EntityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> state { get; set; }
    }
}
